apiVersion: 1

datasources:
  - name: Oura sleep data
    type: postgres
    uid: oura-sleep-data
    access: proxy
    url: $DATABASE_HOST:$DATABASE_PORT
    database: $DATABASE_NAME
    user: $DATABASE_USER
    jsonData:
      sslmode: require
      postgresVersion: 1500
      timescaledb: false
      database: $DATABASE_NAME
    secureJsonData:
      password: $DATABASE_PASSWORD
    isDefault: true
    editable: true
